package com.model;

import java.util.List;

/**
 * TDianpu generated by MyEclipse Persistence Tools
 */

public class TDianpu implements java.io.Serializable
{

	private Integer id;
	private String loginname;
	private String loginpw;
	private String mingcheng;
	
	private String lianxiren;
	private String dianhua;
	private String dizhi;
	private String jieshao;
	
	private String zt;//…Û∫À÷–--…Û∫ÀÕ®π˝
	private String del;
	
	private List goodsList;
	
	
	public String getDel()
	{
		return del;
	}
	public void setDel(String del)
	{
		this.del = del;
	}
	public String getDianhua()
	{
		return dianhua;
	}
	public void setDianhua(String dianhua)
	{
		this.dianhua = dianhua;
	}
	public Integer getId()
	{
		return id;
	}
	
	public void setId(Integer id)
	{
		this.id = id;
	}
	public String getLianxiren()
	{
		return lianxiren;
	}
	public void setLianxiren(String lianxiren)
	{
		this.lianxiren = lianxiren;
	}
	public String getMingcheng()
	{
		return mingcheng;
	}
	
	public String getLoginname()
	{
		return loginname;
	}
	public void setLoginname(String loginname)
	{
		this.loginname = loginname;
	}
	
	public String getZt()
	{
		return zt;
	}
	public void setZt(String zt)
	{
		this.zt = zt;
	}
	public List getGoodsList()
	{
		return goodsList;
	}
	public void setGoodsList(List goodsList)
	{
		this.goodsList = goodsList;
	}
	public String getLoginpw()
	{
		return loginpw;
	}
	public void setLoginpw(String loginpw)
	{
		this.loginpw = loginpw;
	}
	public void setMingcheng(String mingcheng)
	{
		this.mingcheng = mingcheng;
	}
	public String getDizhi()
	{
		return dizhi;
	}
	public void setDizhi(String dizhi)
	{
		this.dizhi = dizhi;
	}
	public String getJieshao()
	{
		return jieshao;
	}
	public void setJieshao(String jieshao)
	{
		this.jieshao = jieshao;
	}

}